[Interface]
# Device: Normal Raptor
PrivateKey = eCObSqPc/wt9oxXkvAehG5LRm/b6cdkjzr5fNWc+BkQ=
Address = 10.64.234.127/32,fc00:bbbb:bbbb:bb01::1:ea7e/128
DNS = 10.64.0.1

[Peer]
PublicKey = 3HtGdhEXUPKQIDRW49wCUoTK2ZXfq+QfzjfYoldNchg=
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 138.199.60.28:51820
[Socks5]
BindAddress = 0.0.0.0:1080
