#
# Use this configuration with WireGuard client
#
[Interface]
Address = 10.14.0.2/16
PrivateKey = iJoe44p+rXSVlML2A6UPXEbAIUP+PpdHOWoVtkjwvGQ=
DNS = 162.252.172.57, 149.154.159.92
[Peer]
PublicKey = MGfgkhJsMVMTO33h1wr76+z6gQr/93VcGdClfbaPsnU=
AllowedIPs = 0.0.0.0/0
Endpoint = sg-sng.prod.surfshark.com:51820
[Socks5]
BindAddress = 0.0.0.0:1080
