[Interface]
# Cloudflare WARP Account ID: 0cf73a0e-5cad-4d0f-80cc-a8373d4cb5a4
Address = 172.16.0.2, 2606:4700:110:80ca:c0a3:844f:ea94:bf09
PrivateKey = IKk4OFyP0/IPeDAEyrOlvKl/GEhhQX6mAU8oMq1mjGM=
DNS = 1.1.1.1, 2606:4700:4700::1111

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = engage.cloudflareclient.com:2408

[Socks5]
BindAddress = 0.0.0.0:1080
