[Interface]
# Cloudflare WARP Account ID: c39afedc-4feb-4fac-8192-b8addd389806
Address = 172.16.0.2, 2606:4700:110:847e:3c02:df6:3e6d:33fb
PrivateKey = +CraM6qLAqIKqzJgy/ZfI6KfVsGtPUIu7rS9P6UtcUM=
DNS = 1.1.1.1, 2606:4700:4700::1111

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = engage.cloudflareclient.com:2408

[Socks5]
BindAddress = 0.0.0.0:1080
