[Interface]
PrivateKey = ADUTRMEDrDN1nhGbYQsb6emkjHy6/igp/a5jywEoFVw=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: sg-sng-st009.prod.surfshark.com [SG/Singapore]
[Peer]
PublicKey = sk0YuJx8nO9hhJnQz5rn1aboekY7Hdl9ZfebCSXBGAY=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = sg-sng-st009.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
