#
# Use this configuration with WireGuard client
#
[Interface]
Address = 10.14.0.2/16
PrivateKey = qCpy04Yc0jwlGjcuHjZQrjo/PA+Rw+2SUGaGmKi0rU8=
DNS = 162.252.172.57, 149.154.159.92
[Peer]
PublicKey = Mioou38fh5H+3LWMpitLOWT3JaDGg2gXxqjl2eXkPFU=
AllowedIPs = 0.0.0.0/0
Endpoint = vn-hcm.prod.surfshark.com:51820
[Socks5]
BindAddress = 0.0.0.0:1080
