[Interface]
PrivateKey = sGQDLt9BygDBVZIXTRC2/Hz7XiwipO+mqb8wCzgTHEs=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: sg-sng-st007.prod.surfshark.com [SG/Singapore]
[Peer]
PublicKey = 4geWIYI3+Zn7GmtzJ4D9/QIhRjWGpWwIhqssT3Yl9RE=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = sg-sng-st007.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
