[Interface]
# Device: Square Stork
PrivateKey = 6HFmZp571CUZIB0/TTcOmKERZgdFPwzOn59FVCxWRX0=
Address = 10.65.0.133/32,fc00:bbbb:bbbb:bb01::2:84/128
DNS = 10.64.0.1

[Peer]
PublicKey = KB6ZA1PAixd74c+mO0VBY4j7LaitK8B4L1APbFIQyQ0=
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 146.70.199.194:51820
[Socks5]
BindAddress = 0.0.0.0:1080
