[Interface]
# Cloudflare WARP Account ID: 6b9af3b5-12b9-4d4b-947a-6471c8c5a3ab
Address = 172.16.0.2, 2606:4700:110:8a44:5213:ad29:35b7:f6e
PrivateKey = gLjgy9r7XLDDNeUfvnvxhjdjqQCkKtBi0wGvVlkDTlg=
DNS = 1.1.1.1, 2606:4700:4700::1111

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = engage.cloudflareclient.com:2408

[Socks5]
BindAddress = 0.0.0.0:1080
