#
# Use this configuration with WireGuard client
#
[Interface]
Address = 10.14.0.2/16
PrivateKey = qK0sW4cgEoqrY+auL7nlAjDDYsOpPInkCA+b64yQQXg=
DNS = 162.252.172.57, 149.154.159.92
[Peer]
PublicKey = qyghLDfpfyparp0M52OVcmhKckayOvbRO2DDLkgJqyk=
AllowedIPs = 0.0.0.0/0
Endpoint = id-jak.prod.surfshark.com:51820
[Socks5]
BindAddress = 0.0.0.0:1080
