[Interface]
PrivateKey = eCObSqPc/wt9oxXkvAehG5LRm/b6cdkjzr5fNWc+BkQ=
Address = 10.64.234.127/32
DNS = 10.64.0.1

# mullvad: my-kul-wg-001 [MY/Kuala Lumpur]
[Peer]
PublicKey = RnwTFcAl6z4UfXio9ApLqlOjBcYvD0gWG0htl6fiCl4=
AllowedIPs = 0.0.0.0/0
Endpoint = 98.98.47.130:51820

[Socks5]
BindAddress = 0.0.0.0:1080
