[Interface]
PrivateKey = 4C8v24OVC8Pf/JKn3AQYDVrBcyv6v0lxFK9UyPQoPlo=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: sg-sng-st008.prod.surfshark.com [SG/Singapore]
[Peer]
PublicKey = 6GvYCh8LaRnbp3OwvNB2BPCaNOjGYKGwfen6eVUP6hc=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = sg-sng-st008.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
