[Interface]
PrivateKey = mMDduHqI3uBKeplhVPcurCA6lcTXPDB0JfTvWU0Jl2M=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: my-kul.prod.surfshark.com [MY/Kuala Lumpur]
[Peer]
PublicKey = AS84LXlJfgBwGHc70MvtGRxsMqNNucZ2pNOBayJUm04=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = my-kul.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
