[Interface]
PrivateKey = GIcoaV4dAC0aJSIeOWUaKLF1s8dsgTTQEbHSrLgWGmo=
Address = 10.69.223.104/32
DNS = 10.64.0.1

# mullvad: id-jpu-wg-002 [ID/Jakarta]
[Peer]
PublicKey = gWsH1w7lTYbsS+WxsE6w6vtXSAJoHM6PhDX5DFMYM1k=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = 129.227.46.162:51820

[Socks5]
BindAddress = 0.0.0.0:1080
