[Interface]
PrivateKey = uM0oq/Ao3AnMoQkObrJ33fWdcjb/NaqvVg2kKQl9JEg=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: sg-sng-st005.prod.surfshark.com [SG/Singapore]
[Peer]
PublicKey = d9+f+QTkJH5vYt5dah62rKQLVIudeMERjEssTg3txnQ=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = sg-sng-st005.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
