[Interface]
PrivateKey = eM/CPrdN1PEyHtoxEE6U4By9kvCMzebLn0bfPcGqLlE=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: sg-sng.prod.surfshark.com [SG/Singapore]
[Peer]
PublicKey = MGfgkhJsMVMTO33h1wr76+z6gQr/93VcGdClfbaPsnU=
AllowedIPs = 0.0.0.0/0
Endpoint = sg-sng.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
