[Interface]
PrivateKey = qCpy04Yc0jwlGjcuHjZQrjo/PA+Rw+2SUGaGmKi0rU8=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: ph-mnl.prod.surfshark.com [PH/Manila]
[Peer]
PublicKey = utXZy1ELBSQKa6s9/K/W4sV11Jod6sSLoikKqKRPyQs=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = ph-mnl.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
