[Interface]
PrivateKey = +PLv2aytTl2E0aVE2L5sa0jZ5R13y8FRLCdwNf6VyUc=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: sg-sng-st006.prod.surfshark.com [SG/Singapore]
[Peer]
PublicKey = r5IE8U+/CmPJBQFULLUPwfE4AESkUU7Z4wWBOpHvFyA=
AllowedIPs = 0.0.0.0/0
Endpoint = sg-sng-st006.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
