[Interface]
PrivateKey = AMGYufne8kfGZNAGcX4JVQhFZF0ShNd33ZbsZ4/xgks=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: th-bkk.prod.surfshark.com [TH/Bangkok]
[Peer]
PublicKey = OoFY46j/w4uQFyFu/OQ/h3x+ymJ1DJ4UR1fwGNxOxk0=
AllowedIPs = 0.0.0.0/0
Endpoint = th-bkk.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
