[Interface]
PrivateKey = aNY1C2I2Yf825GyQZsFYCfFyary/UmQmQSyx+R1qlVQ=
Address = 10.14.0.2/16
DNS = 162.252.172.57, 149.154.159.92

# surfshark: sg-sng-st010.prod.surfshark.com [SG/Singapore]
[Peer]
PublicKey = eL2WOQ130amedxlJ50x71eZUI3QWg8wuqwgqc9vjSRo=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = sg-sng-st010.prod.surfshark.com:51820

[Socks5]
BindAddress = 0.0.0.0:1080
