[Interface]
PrivateKey = qGjlk+SDw974RDu2y5SubH13dFdpdW/yahp6uBbamHA=
Address = 10.71.190.92/32
DNS = 10.64.0.1

# mullvad: id-jpu-wg-001 [ID/Jakarta]
[Peer]
PublicKey = XYQvOrRqu8j521Hy/8+jGRDLZoSAssOvCectyKz350Y=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = 129.227.46.130:51820

[Socks5]
BindAddress = 0.0.0.0:1080
