[Interface]
PrivateKey = 6HFmZp571CUZIB0/TTcOmKERZgdFPwzOn59FVCxWRX0=
Address = 10.65.0.133/32
DNS = 10.64.0.1

# mullvad: ph-mnl-wg-001 [PH/Manila]
[Peer]
PublicKey = hORxMf/YMmN2/8VWOnTCdgGzGfEyXUEQQ5EBfoCyFDM=
AllowedIPs = 0.0.0.0/0
Endpoint = 129.227.118.162:51820

[Socks5]
BindAddress = 0.0.0.0:1080
