[Interface]
PrivateKey = AAxHsqrJGgeyFsaBHDEGTSKdEguVLvhpK83Qu4z37Ek=
Address = 10.65.14.74/32
DNS = 10.64.0.1

# mullvad: sg-sin-wg-003 [SG/Singapore]
[Peer]
PublicKey = 3HtGdhEXUPKQIDRW49wCUoTK2ZXfq+QfzjfYoldNchg=
AllowedIPs = 0.0.0.0/0
Endpoint = 138.199.60.28:51820

[Socks5]
BindAddress = 0.0.0.0:1080
